apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-statefulset
spec:
  serviceName: minio-service
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      securityContext:
        fsGroup: 1001  # fsGroup diterapkan di tingkat pod
      containers:
        - name: minio
          image: minio/minio:RELEASE.2024-06-29T01-20-47Z
          ports:
            - containerPort: 9000
            - containerPort: 9001
          command:
            - minio
            - server
            - /data
            - --console-address
            - :9001
          volumeMounts:
            - name: minio-storage
              mountPath: /data
          envFrom:
            - secretRef:
                name: minio-secrets
          securityContext:
            runAsUser: 1001  # Menjalankan kontainer dengan UID yang sesuai untuk NFS     
            runAsGroup: 1001 # Menjalankan kontainer dengan GID yang sesuai untuk NFS     
      volumes:
        - name: minio-storage
          persistentVolumeClaim:
            claimName: minio-pvc