apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  clusterIP: None  # Penting untuk StatefulSet, memastikan tiap pod dapat diakses secara individu
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306